//! UI views layer.

mod applications;
mod applications_analytics;
mod applications_card;
mod applications_data;
mod applications_drag;
mod applications_list;
mod applications_menu;
mod applications_funnel;
mod applications_snapshot;
mod confirm;
mod diary;
mod diary_capture;
mod diary_use;
mod gallery;
pub mod import_flow;
mod library;
mod library_usage;
mod preset_matrix;
mod root;
mod root_custom_sections;
mod root_highlights;
mod root_layout_rail;
mod root_overlays;
mod root_section_drag;
mod root_section_rename;
mod root_section_variants;
mod root_sidebar;
mod root_dates;
mod root_undo;
pub mod save_status;
pub mod settings_window;
mod setup;
mod shell;
mod sidebar;
mod vault_cache;
mod welcome;

pub use root::{init_keybindings, EditorEvent, ExportPdf, Root};
pub use shell::Shell;
